# Generated by Django 6.0.7 on 2026-09-21 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_seat_type_price_booking_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['seat_number']},
        ),
        migrations.AlterModelOptions(
            name='theater',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='seat',
            name='theater',
        ),
        migrations.RemoveField(
            model_name='seatreservation',
            name='theater',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='date',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='time',
        ),
        migrations.AddField(
            model_name='movie',
            name='end_date',
            field=models.DateField(blank=True, help_text='Last day of theatrical run (inclusive)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.theater'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, help_text='First day of theatrical run', null=True),
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Screen 1, IMAX Hall', max_length=100)),
                ('total_seats', models.PositiveIntegerField(default=100)),
                ('screen_type', models.CharField(choices=[('standard', 'Standard'), ('imax', 'IMAX'), ('3d', '3D'), ('4dx', '4DX'), ('dolby', 'Dolby Atmos')], default='standard', max_length=20)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='movies.theater')),
            ],
            options={
                'ordering': ['theater', 'name'],
                'unique_together': {('theater', 'name')},
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.screen'),
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Screening date')),
                ('start_time', models.TimeField(help_text='Show start time')),
                ('cleaning_buffer_minutes', models.PositiveIntegerField(default=20, help_text='Buffer time after show ends before next show can start (minutes)')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.screen')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.theater')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('screen', 'date', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='show_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.showtime'),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='show_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='movies.showtime'),
        ),
    ]
