# Generated by Django 6.0.7 on 2026-10-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_theater_city_alter_booking_booked_at_bookingorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='booking_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for this movie\'s bookings. Uncheck to immediately block all new bookings and showtime scheduling, regardless of release/end dates. A passed "end_date" alone no longer blocks bookings — toggle this off instead.'),
        ),
    ]
